# GoReleaser v2 Configuration for NeuroShell
# This configuration builds cross-platform binaries and creates GitHub releases

# GoReleaser configuration version
version: 2

# Project metadata
project_name: neuroshell

# Environment variables
env:
  - CGO_ENABLED=0

# Build configuration
builds:
  # Main CLI binary
  - id: neuro
    binary: neuro
    main: ./cmd/neuro
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X 'neuroshell/internal/version.Version={{.Version}}'
      - -X 'neuroshell/internal/version.GitCommit={{.ShortCommit}}'
      - -X 'neuroshell/internal/version.BuildDate={{.Date}}'
    flags:
      - -trimpath

  # Testing binary
  - id: neurotest
    binary: neurotest
    main: ./cmd/neurotest
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X 'neuroshell/internal/version.Version={{.Version}}'
      - -X 'neuroshell/internal/version.GitCommit={{.ShortCommit}}'
      - -X 'neuroshell/internal/version.BuildDate={{.Date}}'
    flags:
      - -trimpath

# Universal binaries for macOS (combine Intel + Apple Silicon)
universal_binaries:
  - id: neuro-universal
    ids:
      - neuro
    replace: false
    name_template: 'neuro'
  - id: neurotest-universal
    ids:
      - neurotest
    replace: false
    name_template: 'neurotest'

# Archive configuration
archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE
      - CLAUDE.md
      - docs/RELEASE_PROCESS.md
      - src: "examples/neurorc/*.neurorc"
        dst: examples/neurorc
        strip_parent: false

  - id: universal
    ids:
      - neuro-universal
      - neurotest-universal
    name_template: "{{ .ProjectName }}_{{ .Version }}_darwin_universal"
    files:
      - README.md
      - LICENSE
      - CLAUDE.md
      - docs/RELEASE_PROCESS.md
      - src: "examples/neurorc/*.neurorc"
        dst: examples/neurorc
        strip_parent: false

# Checksum configuration
checksum:
  name_template: 'checksums.txt'

# Changelog configuration (disable automatic generation)
changelog:
  disable: true

# Release configuration
release:
  github:
    owner: vitadin
    name: NeuroShell
  
  # Release naming with codename integration  
  name_template: >-
    {{- if eq .Version "0.1.0" }}NeuroShell {{ .Version }} 'Hydra'
    {{- else if eq .Version "0.2.0" }}NeuroShell {{ .Version }} 'Planaria'  
    {{- else if eq .Version "0.2.3" }}NeuroShell {{ .Version }} 'Planaria'
    {{- else if eq .Version "0.2.4" }}NeuroShell {{ .Version }} 'Planaria'
    {{- else if eq .Version "0.3.0" }}NeuroShell {{ .Version }} 'Dendro'
    {{- else if eq .Version "0.4.0" }}NeuroShell {{ .Version }} 'Tentara'
    {{- else if eq .Version "0.5.0" }}NeuroShell {{ .Version }} 'Corvex'
    {{- else if eq .Version "0.6.0" }}NeuroShell {{ .Version }} 'Labris'
    {{- else if eq .Version "0.7.0" }}NeuroShell {{ .Version }} 'Primax'
    {{- else if eq .Version "0.8.0" }}NeuroShell {{ .Version }} 'Cognita'
    {{- else if eq .Version "0.9.0" }}NeuroShell {{ .Version }} 'Resonix'
    {{- else if eq .Version "1.0.0" }}NeuroShell {{ .Version }} 'Saprix'
    {{- else if eq .Version "2.0.0" }}NeuroShell {{ .Version }} 'Omnix'
    {{- else }}NeuroShell {{ .Version }}
    {{- end }}

  prerelease: auto
  mode: replace
  
  header: |
    ## 🧠 NeuroShell Release
    
    Advanced AI shell environment for seamless LLM interaction and automation.
  
  footer: |
    **Full Changelog**: Use `\change-log-show` command to view the complete changelog
    
    ---
    
    🐛 **Found a bug?** [Report it here](https://github.com/vitadin/NeuroShell/issues/new)
    💡 **Have a feature request?** [Let us know](https://github.com/vitadin/NeuroShell/discussions)
    📖 **Documentation**: [NeuroShell Docs](https://github.com/vitadin/NeuroShell/blob/main/CLAUDE.md)

# Milestones
milestones:
  - close: true
    fail_on_error: false
    name_template: '{{ .Version }}'